# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=500, verbose_name='Post content')),
                ('up_votes', models.PositiveIntegerField(default=0, verbose_name='Up votes')),
                ('down_votes', models.PositiveIntegerField(default=0, verbose_name='Down votes')),
            ],
        ),
    ]
