# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0002_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.FloatField(default=0, verbose_name='Post Score'),
        ),
    ]
